In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import kagglehub

# Download latest version
DATASET_PATH = kagglehub.dataset_download("joebeachcapital/windows-malwares")

print("Dataset downloaded to:")
print(DATASET_PATH)

Mounting files to /kaggle/input/datasets/joebeachcapital/windows-malwares...
Dataset downloaded to:
/kaggle/input/datasets/joebeachcapital/windows-malwares

In [3]:
import os

print("Files in dataset:\n")

for file in sorted(os.listdir(DATASET_PATH)):
    print(file)

Files in dataset:

API_Functions.csv
DLLs_Imported.csv
PE_Header.csv
PE_Section.csv

In [4]:
import os

for file in sorted(os.listdir(DATASET_PATH)):
    path = os.path.join(DATASET_PATH, file)

    size_gb = os.path.getsize(path) / (1024**3)

    print(f"{file:<25} {size_gb:.2f} GB")

API_Functions.csv         1.21 GB
DLLs_Imported.csv         0.04 GB
PE_Header.csv             0.01 GB
PE_Section.csv            0.01 GB

In [8]:
import numpy as np

api_cols = api_df.columns.drop(["SHA256", "Type"])

api_df[api_cols] = api_df[api_cols].astype(np.uint8)

api_df["Type"] = api_df["Type"].astype(np.uint8)

api_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29505 entries, 0 to 29504
Columns: 21920 entries, SHA256 to setupdigethwprofilefriendlynameexw
dtypes: object(1), uint8(21919)
memory usage: 619.9 MB

In [9]:
api_df.to_parquet(
    "API_Functions_Optimized.parquet",
    index=False
)

In [1]:
import pandas as pd
import numpy as np

# ==========================
# Load Dataset
# ==========================

dll_df = pd.read_csv(
    "/kaggle/input/datasets/joebeachcapital/windows-malwares/DLLs_Imported.csv"
)

print("="*80)
print("Basic Information")
print("="*80)

print("Shape:", dll_df.shape)

print("\nFirst 5 rows")
display(dll_df.head())

print("\nFirst 20 columns")
print(dll_df.columns[:20])

print("\nLast 20 columns")
print(dll_df.columns[-20:])

print("\nData Types")
print(dll_df.dtypes.value_counts())

print("\nMemory Usage")
dll_df.info(memory_usage="deep")

# ==========================
# Memory Optimization
# ==========================

dll_cols = dll_df.columns.drop(["SHA256", "Type"])

dll_df[dll_cols] = dll_df[dll_cols].astype(np.uint8)
dll_df["Type"] = dll_df["Type"].astype(np.uint8)

print("\nAfter Optimization")
dll_df.info(memory_usage="deep")

# ==========================
# Save Optimized Version
# ==========================

dll_df.to_parquet(
    "DLLs_Imported_Optimized.parquet",
    index=False
)

# ==========================
# Label Distribution
# ==========================

print("\nLabel Distribution")
print(dll_df["Type"].value_counts())

print("\nLabel Proportion")
print(dll_df["Type"].value_counts(normalize=True))

# ==========================
# DLL Frequency
# ==========================

dll_usage = dll_df.drop(columns=["SHA256", "Type"]).sum()

print("\nDLL Usage Statistics")
print(dll_usage.describe())

print("\nTop 30 DLLs")
print(dll_usage.sort_values(ascending=False).head(30))

print("\nLeast Used DLLs")
print(dll_usage.sort_values().head(30))

# ==========================
# Sparsity
# ==========================

print("\nDLLs appearing exactly once:")
print((dll_usage == 1).sum())

print("\nDLLs appearing <5 times:")
print((dll_usage < 5).sum())

print("\nDLLs appearing <10 times:")
print((dll_usage < 10).sum())

# ==========================
# Quality Checks
# ==========================

print("\nUnused DLL columns:")
print((dll_usage == 0).sum())

constant_cols = [
    col for col in dll_df.columns[2:]
    if dll_df[col].nunique() == 1
]

print("\nConstant Columns:")
print(len(constant_cols))

================================================================================
Basic Information
================================================================================
Shape: (29498, 631)

First 5 rows

,SHA256,Type,advapi32.dll,kernel32.dll,vspmsg.dll,ole32.dll,oleaut32.dll,psapi.dll,setupapi.dll,shlwapi.dll,...,odbccp32.dll,api-ms-win-crt-environment-l1-1-0.dll,api-ms-win-core-memory-l1-1-3.dll,api-ms-win-core-datetime-l1-1-0.dll,api-ms-win-core-psapi-ansi-l1-1-0.dll,api-ms-win-core-fibers-l1-1-0.dll,api-ms-win-core-file-l2-1-0.dll,api-ms-win-core-sysinfo-l1-2-0.dll,dbgeng.dll,d3d11.dll
0,002ce0d28ec990aadbbc89df457189de37d8adaadc9c08...,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2a053f32b1d48539e3e2807f86754be87ce95b08378467...,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2f031a1752f7067fb9f483ae0ac5f3036c9b66cc4af40e...,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,308e8bb2e8a3b67607d2454370e0b50147b42049bda813...,0,1,1,0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,31aaba443b9869e6e68c17125f8d7989cbd762fb38ae3a...,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

First 20 columns
Index(['SHA256', 'Type', 'advapi32.dll', 'kernel32.dll', 'vspmsg.dll',
       'ole32.dll', 'oleaut32.dll', 'psapi.dll', 'setupapi.dll', 'shlwapi.dll',
       'pdh.dll', 'xmllite.dll', 'msvcr110.dll', 'user32.dll', 'msvcrt.dll',
       'shell32.dll', 'ntdll.dll', 'api-ms-win-core-winrt-l1-1-0.dll',
       'dui70.dll', 'windows.ui.immersive.dll'],
      dtype='object')

Last 20 columns
Index(['api-ms-win-core-console-l3-2-0.dll',
       'api-ms-win-core-localization-l1-2-0.dll',
       'api-ms-win-core-errorhandling-l1-1-0.dll',
       'api-ms-win-core-processthreads-l1-1-1.dll',
       'api-ms-win-core-interlocked-l1-1-0.dll',
       'api-ms-win-core-debug-l1-1-0.dll',
       'api-ms-win-core-rtlsupport-l1-1-0.dll',
       'api-ms-win-core-file-l1-1-0.dll', 'api-ms-win-core-heap-l1-1-0.dll',
       'api-ms-win-ntuser-sysparams-l1-1-0.dll', 'odbccp32.dll',
       'api-ms-win-crt-environment-l1-1-0.dll',
       'api-ms-win-core-memory-l1-1-3.dll',
       'api-ms-win-core-datetime-l1-1-0.dll',
       'api-ms-win-core-psapi-ansi-l1-1-0.dll',
       'api-ms-win-core-fibers-l1-1-0.dll', 'api-ms-win-core-file-l2-1-0.dll',
       'api-ms-win-core-sysinfo-l1-2-0.dll', 'dbgeng.dll', 'd3d11.dll'],
      dtype='object')

Data Types
int64     630
object      1
Name: count, dtype: int64

Memory Usage
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29498 entries, 0 to 29497
Columns: 631 entries, SHA256 to d3d11.dll
dtypes: int64(630), object(1)
memory usage: 145.0 MB

After Optimization
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29498 entries, 0 to 29497
Columns: 631 entries, SHA256 to d3d11.dll
dtypes: object(1), uint8(630)
memory usage: 20.9 MB

Label Distribution
Type
4    5076
1    5022
3    4957
2    4643
5    4224
6    3699
0    1877
Name: count, dtype: int64

Label Proportion
Type
4    0.172079
1    0.170249
3    0.168045
2    0.157401
5    0.143196
6    0.125398
0    0.063631
Name: proportion, dtype: float64

DLL Usage Statistics
count      629.000000
mean       147.887122
std       1020.206412
min          1.000000
25%          1.000000
50%          2.000000
75%          8.000000
max      14598.000000
dtype: float64

Top 30 DLLs
kernel32.dll    14598
mscoree.dll     12374
user32.dll      11160
gdi32.dll        7678
advapi32.dll     6625
comctl32.dll     3720
shell32.dll      3295
msvbvm60.dll     3140
oleaut32.dll     3122
ole32.dll        3100
msvcrt.dll       2060
version.dll      1766
winmm.dll        1702
comdlg32.dll     1517
shlwapi.dll      1342
mfc42.dll        1039
msimg32.dll       955
winhttp.dll       787
winspool.drv      668
gdiplus.dll       656
oledlg.dll        482
oleacc.dll        439
shfolder.dll      420
ws2_32.dll        365
imagehlp.dll      352
msvcr90.dll       329
msvcp90.dll       290
psapi.dll         285
ncrypt.dll        254
wininet.dll       236
dtype: uint64

Least Used DLLs
zip7module.dll       1
ggdownloader.dll     1
ggspawn.dll          1
dibmodule.dll        1
fileloader.dll       1
sqlite3.dll          1
difxapi.dll          1
filesystem.dll       1
oisapp.dll           1
libgeos_c-1.dll      1
libfreetype-6.dll    1
libexpat-1.dll       1
libcurl-4.dll        1
yaml.dll             1
zlib.dll             1
libcrypto-1_1.dll    1
mf.dll               1
zipfldr.dll          1
wship6.dll           1
themeui.dll          1
msls31.dll           1
msctf.dll            1
kbdusl.dll           1
kbdlt1.dll           1
kbdhe319.dll         1
hhctrl.ocx           1
pstorec.dll          1
oleprn.dll           1
msimtf.dll           1
mspdbcore.dll        1
dtype: uint64

DLLs appearing exactly once:
274

DLLs appearing <5 times:
431

DLLs appearing <10 times:
487

Unused DLL columns:
0

Constant Columns:
0

In [2]:
import pandas as pd
import numpy as np

# ==========================
# Load Dataset
# ==========================

pe_df = pd.read_csv(
    "/kaggle/input/datasets/joebeachcapital/windows-malwares/PE_Header.csv"
)

print("="*80)
print("Basic Information")
print("="*80)

print("Shape:", pe_df.shape)

display(pe_df.head())

print("\nColumns")
print(pe_df.columns.tolist())

print("\nData Types")
print(pe_df.dtypes.value_counts())

print("\nMemory Usage")
pe_df.info(memory_usage="deep")

# ==========================
# Optimize
# ==========================

# Optimize only the label
pe_df["Type"] = pe_df["Type"].astype(np.uint8)

print("\nAfter Optimization")
pe_df.info(memory_usage="deep")

# Save optimized version
pe_df.to_parquet(
    "PE_Header_Optimized.parquet",
    index=False
)

# ==========================
# Label Distribution
# ==========================

print("\nLabel Distribution")
print(pe_df["Type"].value_counts())

# ==========================
# Missing Values
# ==========================

print("\nMissing Values")
print(pe_df.isnull().sum().sort_values(ascending=False).head(20))

# ==========================
# Constant Columns
# ==========================

constant_cols = []

for col in pe_df.columns[2:]:
    if pe_df[col].nunique() == 1:
        constant_cols.append(col)

print("\nConstant Columns")
print(len(constant_cols))
print(constant_cols)

# ==========================
# Numerical Summary
# ==========================

print("\nStatistical Summary")
display(pe_df.describe())

================================================================================
Basic Information
================================================================================
Shape: (29807, 54)

,SHA256,Type,e_magic,e_cblp,e_cp,e_crlc,e_cparhdr,e_minalloc,e_maxalloc,e_ss,...,SizeOfImage,SizeOfHeaders,CheckSum,Subsystem,DllCharacteristics,SizeOfStackReserve,SizeOfHeapReserve,SizeOfHeapCommit,LoaderFlags,NumberOfRvaAndSizes
0,dacbe8cb72dd746539792a50e84965fefef73feaa07b5d...,0,23117,144,3,0,4,0,65535,0,...,139264,4096,0,2,1344,1048576,1048576,4096,0,16
1,d3dc7512ce75db33b2c3063fa99245e9ca9fe3b086462f...,0,23117,144,3,0,4,0,65535,0,...,49152,512,0,2,34112,1048576,1048576,4096,0,16
2,b350fac81533f02981dc2176ed17163177d92d9405758e...,0,23117,144,3,0,4,0,65535,0,...,532480,512,0,2,34144,1048576,1048576,4096,0,16
3,dfee618043a47b7b09305df0ca460559d9f567ee246c7b...,0,23117,144,3,0,4,0,65535,0,...,1368064,4096,1366781,2,1024,1048576,1048576,4096,0,16
4,c7b2e4e4fb2fcc44c953673ff57c3d14bdf5d2008f35e9...,0,23117,144,3,0,4,0,65535,0,...,32768,512,64362,2,1344,1048576,1048576,4096,0,16

Columns
['SHA256', 'Type', 'e_magic', 'e_cblp', 'e_cp', 'e_crlc', 'e_cparhdr', 'e_minalloc', 'e_maxalloc', 'e_ss', 'e_sp', 'e_csum', 'e_ip', 'e_cs', 'e_lfarlc', 'e_ovno', 'e_oemid', 'e_oeminfo', 'e_lfanew', 'Machine', 'NumberOfSections', 'TimeDateStamp', 'PointerToSymbolTable', 'NumberOfSymbols', 'SizeOfOptionalHeader', 'Characteristics', 'Magic', 'MajorLinkerVersion', 'MinorLinkerVersion', 'SizeOfCode', 'SizeOfInitializedData', 'SizeOfUninitializedData', 'AddressOfEntryPoint', 'BaseOfCode', 'ImageBase', 'SectionAlignment', 'FileAlignment', 'MajorOperatingSystemVersion', 'MinorOperatingSystemVersion', 'MajorImageVersion', 'MinorImageVersion', 'MajorSubsystemVersion', 'MinorSubsystemVersion', 'Reserved1', 'SizeOfImage', 'SizeOfHeaders', 'CheckSum', 'Subsystem', 'DllCharacteristics', 'SizeOfStackReserve', 'SizeOfHeapReserve', 'SizeOfHeapCommit', 'LoaderFlags', 'NumberOfRvaAndSizes']

Data Types
int64     53
object     1
Name: count, dtype: int64

Memory Usage
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29807 entries, 0 to 29806
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SHA256                       29807 non-null  object
 1   Type                         29807 non-null  int64
 2   e_magic                      29807 non-null  int64
 3   e_cblp                       29807 non-null  int64
 4   e_cp                         29807 non-null  int64
 5   e_crlc                       29807 non-null  int64
 6   e_cparhdr                    29807 non-null  int64
 7   e_minalloc                   29807 non-null  int64
 8   e_maxalloc                   29807 non-null  int64
 9   e_ss                         29807 non-null  int64
 10  e_sp                         29807 non-null  int64
 11  e_csum                       29807 non-null  int64
 12  e_ip                         29807 non-null  int64
 13  e_cs                         29807 non-null  int64
 14  e_lfarlc                     29807 non-null  int64
 15  e_ovno                       29807 non-null  int64
 16  e_oemid                      29807 non-null  int64
 17  e_oeminfo                    29807 non-null  int64
 18  e_lfanew                     29807 non-null  int64
 19  Machine                      29807 non-null  int64
 20  NumberOfSections             29807 non-null  int64
 21  TimeDateStamp                29807 non-null  int64
 22  PointerToSymbolTable         29807 non-null  int64
 23  NumberOfSymbols              29807 non-null  int64
 24  SizeOfOptionalHeader         29807 non-null  int64
 25  Characteristics              29807 non-null  int64
 26  Magic                        29807 non-null  int64
 27  MajorLinkerVersion           29807 non-null  int64
 28  MinorLinkerVersion           29807 non-null  int64
 29  SizeOfCode                   29807 non-null  int64
 30  SizeOfInitializedData        29807 non-null  int64
 31  SizeOfUninitializedData      29807 non-null  int64
 32  AddressOfEntryPoint          29807 non-null  int64
 33  BaseOfCode                   29807 non-null  int64
 34  ImageBase                    29807 non-null  int64
 35  SectionAlignment             29807 non-null  int64
 36  FileAlignment                29807 non-null  int64
 37  MajorOperatingSystemVersion  29807 non-null  int64
 38  MinorOperatingSystemVersion  29807 non-null  int64
 39  MajorImageVersion            29807 non-null  int64
 40  MinorImageVersion            29807 non-null  int64
 41  MajorSubsystemVersion        29807 non-null  int64
 42  MinorSubsystemVersion        29807 non-null  int64
 43  Reserved1                    29807 non-null  int64
 44  SizeOfImage                  29807 non-null  int64
 45  SizeOfHeaders                29807 non-null  int64
 46  CheckSum                     29807 non-null  int64
 47  Subsystem                    29807 non-null  int64
 48  DllCharacteristics           29807 non-null  int64
 49  SizeOfStackReserve           29807 non-null  int64
 50  SizeOfHeapReserve            29807 non-null  int64
 51  SizeOfHeapCommit             29807 non-null  int64
 52  LoaderFlags                  29807 non-null  int64
 53  NumberOfRvaAndSizes          29807 non-null  int64
dtypes: int64(53), object(1)
memory usage: 15.3 MB

After Optimization
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29807 entries, 0 to 29806
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SHA256                       29807 non-null  object
 1   Type                         29807 non-null  uint8
 2   e_magic                      29807 non-null  int64
 3   e_cblp                       29807 non-null  int64
 4   e_cp                         29807 non-null  int64
 5   e_crlc                       29807 non-null  int64
 6   e_cparhdr                    29807 non-null  int64
 7   e_minalloc                   29807 non-null  int64
 8   e_maxalloc                   29807 non-null  int64
 9   e_ss                         29807 non-null  int64
 10  e_sp                         29807 non-null  int64
 11  e_csum                       29807 non-null  int64
 12  e_ip                         29807 non-null  int64
 13  e_cs                         29807 non-null  int64
 14  e_lfarlc                     29807 non-null  int64
 15  e_ovno                       29807 non-null  int64
 16  e_oemid                      29807 non-null  int64
 17  e_oeminfo                    29807 non-null  int64
 18  e_lfanew                     29807 non-null  int64
 19  Machine                      29807 non-null  int64
 20  NumberOfSections             29807 non-null  int64
 21  TimeDateStamp                29807 non-null  int64
 22  PointerToSymbolTable         29807 non-null  int64
 23  NumberOfSymbols              29807 non-null  int64
 24  SizeOfOptionalHeader         29807 non-null  int64
 25  Characteristics              29807 non-null  int64
 26  Magic                        29807 non-null  int64
 27  MajorLinkerVersion           29807 non-null  int64
 28  MinorLinkerVersion           29807 non-null  int64
 29  SizeOfCode                   29807 non-null  int64
 30  SizeOfInitializedData        29807 non-null  int64
 31  SizeOfUninitializedData      29807 non-null  int64
 32  AddressOfEntryPoint          29807 non-null  int64
 33  BaseOfCode                   29807 non-null  int64
 34  ImageBase                    29807 non-null  int64
 35  SectionAlignment             29807 non-null  int64
 36  FileAlignment                29807 non-null  int64
 37  MajorOperatingSystemVersion  29807 non-null  int64
 38  MinorOperatingSystemVersion  29807 non-null  int64
 39  MajorImageVersion            29807 non-null  int64
 40  MinorImageVersion            29807 non-null  int64
 41  MajorSubsystemVersion        29807 non-null  int64
 42  MinorSubsystemVersion        29807 non-null  int64
 43  Reserved1                    29807 non-null  int64
 44  SizeOfImage                  29807 non-null  int64
 45  SizeOfHeaders                29807 non-null  int64
 46  CheckSum                     29807 non-null  int64
 47  Subsystem                    29807 non-null  int64
 48  DllCharacteristics           29807 non-null  int64
 49  SizeOfStackReserve           29807 non-null  int64
 50  SizeOfHeapReserve            29807 non-null  int64
 51  SizeOfHeapCommit             29807 non-null  int64
 52  LoaderFlags                  29807 non-null  int64
 53  NumberOfRvaAndSizes          29807 non-null  int64
dtypes: int64(52), object(1), uint8(1)
memory usage: 15.1 MB

Label Distribution
Type
4    5104
1    5047
3    4973
2    4864
5    4236
6    3706
0    1877
Name: count, dtype: int64

Missing Values
SHA256        0
Type          0
e_magic       0
e_cblp        0
e_cp          0
e_crlc        0
e_cparhdr     0
e_minalloc    0
e_maxalloc    0
e_ss          0
e_sp          0
e_csum        0
e_ip          0
e_cs          0
e_lfarlc      0
e_ovno        0
e_oemid       0
e_oeminfo     0
e_lfanew      0
Machine       0
dtype: int64

Constant Columns
2
['e_magic', 'LoaderFlags']

Statistical Summary

,Type,e_magic,e_cblp,e_cp,e_crlc,e_cparhdr,e_minalloc,e_maxalloc,e_ss,e_sp,...,SizeOfImage,SizeOfHeaders,CheckSum,Subsystem,DllCharacteristics,SizeOfStackReserve,SizeOfHeapReserve,SizeOfHeapCommit,LoaderFlags,NumberOfRvaAndSizes
count,29807.000000,29807.0,29807.000000,29807.000000,29807.000000,29807.000000,29807.000000,29807.000000,29807.000000,29807.000000,...,2.980700e+04,29807.000000,2.980700e+04,29807.000000,29807.000000,2.980700e+04,2.980700e+04,29807.000000,29807.0,29807.000000
mean,3.137719,23117.0,251.805415,754.102593,404.025464,43.835576,354.468078,64788.852551,198.975778,378.190425,...,1.867389e+06,1452.845305,1.106016e+06,2.077901,23421.903177,1.090262e+06,1.063879e+06,4096.420136,0.0,15.991445
std,1.801958,0.0,1532.495681,6583.983720,3640.873340,1290.672177,3120.411120,6421.027708,1810.405076,2324.751433,...,6.605455e+06,1365.458901,4.201892e+07,0.268020,15721.665448,5.435179e+05,2.304633e+05,245.286161,0.0,0.101127
min,0.000000,23117.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.048000e+04,512.000000,0.000000e+00,2.000000,0.000000,0.000000e+00,8.850000e+02,0.000000,0.0,14.000000
25%,2.000000,23117.0,144.000000,3.000000,0.000000,4.000000,0.000000,65535.000000,0.000000,184.000000,...,2.457600e+05,512.000000,0.000000e+00,2.000000,0.000000,1.048576e+06,1.048576e+06,4096.000000,0.0,16.000000
50%,3.000000,23117.0,144.000000,3.000000,0.000000,4.000000,0.000000,65535.000000,0.000000,184.000000,...,4.997120e+05,1024.000000,0.000000e+00,2.000000,33024.000000,1.048576e+06,1.048576e+06,4096.000000,0.0,16.000000
75%,5.000000,23117.0,144.000000,3.000000,0.000000,4.000000,0.000000,65535.000000,0.000000,184.000000,...,9.441280e+05,1024.000000,3.386080e+05,2.000000,34112.000000,1.048576e+06,1.048576e+06,4096.000000,0.0,16.000000
max,6.000000,23117.0,64110.000000,62388.000000,63030.000000,64913.000000,57879.000000,65535.000000,59756.000000,64539.000000,...,1.225933e+08,8192.000000,3.885444e+09,3.000000,50496.000000,6.710886e+07,4.194304e+06,16384.000000,0.0,16.000000

In [3]:
import pandas as pd
import numpy as np

# ==========================
# Load Dataset
# ==========================

section_df = pd.read_csv(
    "/kaggle/input/datasets/joebeachcapital/windows-malwares/PE_Section.csv"
)

print("="*80)
print("Basic Information")
print("="*80)

print("Shape:", section_df.shape)

display(section_df.head())

print("\nColumns")
print(section_df.columns.tolist())

print("\nData Types")
print(section_df.dtypes.value_counts())

print("\nMemory Usage")
section_df.info(memory_usage="deep")

# ==========================
# Optimize
# ==========================

section_df["Type"] = section_df["Type"].astype(np.uint8)

print("\nAfter Optimization")
section_df.info(memory_usage="deep")

section_df.to_parquet(
    "PE_Section_Optimized.parquet",
    index=False
)

# ==========================
# Label Distribution
# ==========================

print("\nLabel Distribution")
print(section_df["Type"].value_counts())

# ==========================
# Missing Values
# ==========================

print("\nTop Missing Values")
print(section_df.isnull().sum().sort_values(ascending=False).head(20))

# ==========================
# Constant Columns
# ==========================

constant_cols = [
    col for col in section_df.columns[2:]
    if section_df[col].nunique() == 1
]

print("\nConstant Columns")
print(len(constant_cols))
print(constant_cols)

# ==========================
# Numerical Summary
# ==========================

display(section_df.describe())

================================================================================
Basic Information
================================================================================
Shape: (29760, 92)

,SHA256,Type,text_Misc_VirtualSize,text_VirtualAddress,text_SizeOfRawData,text_PointerToRawData,text_PointerToRelocations,text_PointerToLinenumbers,text_NumberOfRelocations,text_NumberOfLinenumbers,...,tls_Characteristics,pdata_Misc_VirtualSize,pdata_VirtualAddress,pdata_SizeOfRawData,pdata_PointerToRawData,pdata_PointerToRelocations,pdata_PointerToLinenumbers,pdata_NumberOfRelocations,pdata_NumberOfLinenumbers,pdata_Characteristics
0,dacbe8cb72dd746539792a50e84965fefef73feaa07b5d...,0,114580,8192,114688,4096,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,d3dc7512ce75db33b2c3063fa99245e9ca9fe3b086462f...,0,16436,8192,16896,512,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,b350fac81533f02981dc2176ed17163177d92d9405758e...,0,506420,8192,506880,512,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,dfee618043a47b7b09305df0ca460559d9f567ee246c7b...,0,1312036,8192,1314816,4096,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,c7b2e4e4fb2fcc44c953673ff57c3d14bdf5d2008f35e9...,0,2660,8192,3072,512,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Columns
['SHA256', 'Type', 'text_Misc_VirtualSize', 'text_VirtualAddress', 'text_SizeOfRawData', 'text_PointerToRawData', 'text_PointerToRelocations', 'text_PointerToLinenumbers', 'text_NumberOfRelocations', 'text_NumberOfLinenumbers', 'text_Characteristics', 'data_Misc_VirtualSize', 'data_VirtualAddress', 'data_SizeOfRawData', 'data_PointerToRawData', 'data_PointerToRelocations', 'data_PointerToLinenumbers', 'data_NumberOfRelocations', 'data_NumberOfLinenumbers', 'data_Characteristics', 'rdata_Misc_VirtualSize', 'rdata_VirtualAddress', 'rdata_SizeOfRawData', 'rdata_PointerToRawData', 'rdata_PointerToRelocations', 'rdata_PointerToLinenumbers', 'rdata_NumberOfRelocations', 'rdata_NumberOfLinenumbers', 'rdata_Characteristics', 'bss_Misc_VirtualSize', 'bss_VirtualAddress', 'bss_SizeOfRawData', 'bss_PointerToRawData', 'bss_PointerToRelocations', 'bss_PointerToLinenumbers', 'bss_NumberOfRelocations', 'bss_NumberOfLinenumbers', 'bss_Characteristics', 'idata_Misc_VirtualSize', 'idata_VirtualAddress', 'idata_SizeOfRawData', 'idata_PointerToRawData', 'idata_PointerToRelocations', 'idata_PointerToLinenumbers', 'idata_NumberOfRelocations', 'idata_NumberOfLinenumbers', 'idata_Characteristics', 'edata_Misc_VirtualSize', 'edata_VirtualAddress', 'edata_SizeOfRawData', 'edata_PointerToRawData', 'edata_PointerToRelocations', 'edata_PointerToLinenumbers', 'edata_NumberOfRelocations', 'edata_NumberOfLinenumbers', 'edata_Characteristics', 'rsrc_Misc_VirtualSize', 'rsrc_VirtualAddress', 'rsrc_SizeOfRawData', 'rsrc_PointerToRawData', 'rsrc_PointerToRelocations', 'rsrc_PointerToLinenumbers', 'rsrc_NumberOfRelocations', 'rsrc_NumberOfLinenumbers', 'rsrc_Characteristics', 'reloc_Misc_VirtualSize', 'reloc_VirtualAddress', 'reloc_SizeOfRawData', 'reloc_PointerToRawData', 'reloc_PointerToRelocations', 'reloc_PointerToLinenumbers', 'reloc_NumberOfRelocations', 'reloc_NumberOfLinenumbers', 'reloc_Characteristics', 'tls_Misc_VirtualSize', 'tls_VirtualAddress', 'tls_SizeOfRawData', 'tls_PointerToRawData', 'tls_PointerToRelocations', 'tls_PointerToLinenumbers', 'tls_NumberOfRelocations', 'tls_NumberOfLinenumbers', 'tls_Characteristics', 'pdata_Misc_VirtualSize', 'pdata_VirtualAddress', 'pdata_SizeOfRawData', 'pdata_PointerToRawData', 'pdata_PointerToRelocations', 'pdata_PointerToLinenumbers', 'pdata_NumberOfRelocations', 'pdata_NumberOfLinenumbers', 'pdata_Characteristics']

Data Types
int64     91
object     1
Name: count, dtype: int64

Memory Usage
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29760 entries, 0 to 29759
Data columns (total 92 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SHA256                      29760 non-null  object
 1   Type                        29760 non-null  int64
 2   text_Misc_VirtualSize       29760 non-null  int64
 3   text_VirtualAddress         29760 non-null  int64
 4   text_SizeOfRawData          29760 non-null  int64
 5   text_PointerToRawData       29760 non-null  int64
 6   text_PointerToRelocations   29760 non-null  int64
 7   text_PointerToLinenumbers   29760 non-null  int64
 8   text_NumberOfRelocations    29760 non-null  int64
 9   text_NumberOfLinenumbers    29760 non-null  int64
 10  text_Characteristics        29760 non-null  int64
 11  data_Misc_VirtualSize       29760 non-null  int64
 12  data_VirtualAddress         29760 non-null  int64
 13  data_SizeOfRawData          29760 non-null  int64
 14  data_PointerToRawData       29760 non-null  int64
 15  data_PointerToRelocations   29760 non-null  int64
 16  data_PointerToLinenumbers   29760 non-null  int64
 17  data_NumberOfRelocations    29760 non-null  int64
 18  data_NumberOfLinenumbers    29760 non-null  int64
 19  data_Characteristics        29760 non-null  int64
 20  rdata_Misc_VirtualSize      29760 non-null  int64
 21  rdata_VirtualAddress        29760 non-null  int64
 22  rdata_SizeOfRawData         29760 non-null  int64
 23  rdata_PointerToRawData      29760 non-null  int64
 24  rdata_PointerToRelocations  29760 non-null  int64
 25  rdata_PointerToLinenumbers  29760 non-null  int64
 26  rdata_NumberOfRelocations   29760 non-null  int64
 27  rdata_NumberOfLinenumbers   29760 non-null  int64
 28  rdata_Characteristics       29760 non-null  int64
 29  bss_Misc_VirtualSize        29760 non-null  int64
 30  bss_VirtualAddress          29760 non-null  int64
 31  bss_SizeOfRawData           29760 non-null  int64
 32  bss_PointerToRawData        29760 non-null  int64
 33  bss_PointerToRelocations    29760 non-null  int64
 34  bss_PointerToLinenumbers    29760 non-null  int64
 35  bss_NumberOfRelocations     29760 non-null  int64
 36  bss_NumberOfLinenumbers     29760 non-null  int64
 37  bss_Characteristics         29760 non-null  int64
 38  idata_Misc_VirtualSize      29760 non-null  int64
 39  idata_VirtualAddress        29760 non-null  int64
 40  idata_SizeOfRawData         29760 non-null  int64
 41  idata_PointerToRawData      29760 non-null  int64
 42  idata_PointerToRelocations  29760 non-null  int64
 43  idata_PointerToLinenumbers  29760 non-null  int64
 44  idata_NumberOfRelocations   29760 non-null  int64
 45  idata_NumberOfLinenumbers   29760 non-null  int64
 46  idata_Characteristics       29760 non-null  int64
 47  edata_Misc_VirtualSize      29760 non-null  int64
 48  edata_VirtualAddress        29760 non-null  int64
 49  edata_SizeOfRawData         29760 non-null  int64
 50  edata_PointerToRawData      29760 non-null  int64
 51  edata_PointerToRelocations  29760 non-null  int64
 52  edata_PointerToLinenumbers  29760 non-null  int64
 53  edata_NumberOfRelocations   29760 non-null  int64
 54  edata_NumberOfLinenumbers   29760 non-null  int64
 55  edata_Characteristics       29760 non-null  int64
 56  rsrc_Misc_VirtualSize       29760 non-null  int64
 57  rsrc_VirtualAddress         29760 non-null  int64
 58  rsrc_SizeOfRawData          29760 non-null  int64
 59  rsrc_PointerToRawData       29760 non-null  int64
 60  rsrc_PointerToRelocations   29760 non-null  int64
 61  rsrc_PointerToLinenumbers   29760 non-null  int64
 62  rsrc_NumberOfRelocations    29760 non-null  int64
 63  rsrc_NumberOfLinenumbers    29760 non-null  int64
 64  rsrc_Characteristics        29760 non-null  int64
 65  reloc_Misc_VirtualSize      29760 non-null  int64
 66  reloc_VirtualAddress        29760 non-null  int64
 67  reloc_SizeOfRawData         29760 non-null  int64
 68  reloc_PointerToRawData      29760 non-null  int64
 69  reloc_PointerToRelocations  29760 non-null  int64
 70  reloc_PointerToLinenumbers  29760 non-null  int64
 71  reloc_NumberOfRelocations   29760 non-null  int64
 72  reloc_NumberOfLinenumbers   29760 non-null  int64
 73  reloc_Characteristics       29760 non-null  int64
 74  tls_Misc_VirtualSize        29760 non-null  int64
 75  tls_VirtualAddress          29760 non-null  int64
 76  tls_SizeOfRawData           29760 non-null  int64
 77  tls_PointerToRawData        29760 non-null  int64
 78  tls_PointerToRelocations    29760 non-null  int64
 79  tls_PointerToLinenumbers    29760 non-null  int64
 80  tls_NumberOfRelocations     29760 non-null  int64
 81  tls_NumberOfLinenumbers     29760 non-null  int64
 82  tls_Characteristics         29760 non-null  int64
 83  pdata_Misc_VirtualSize      29760 non-null  int64
 84  pdata_VirtualAddress        29760 non-null  int64
 85  pdata_SizeOfRawData         29760 non-null  int64
 86  pdata_PointerToRawData      29760 non-null  int64
 87  pdata_PointerToRelocations  29760 non-null  int64
 88  pdata_PointerToLinenumbers  29760 non-null  int64
 89  pdata_NumberOfRelocations   29760 non-null  int64
 90  pdata_NumberOfLinenumbers   29760 non-null  int64
 91  pdata_Characteristics       29760 non-null  int64
dtypes: int64(91), object(1)
memory usage: 23.9 MB

After Optimization
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29760 entries, 0 to 29759
Data columns (total 92 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SHA256                      29760 non-null  object
 1   Type                        29760 non-null  uint8
 2   text_Misc_VirtualSize       29760 non-null  int64
 3   text_VirtualAddress         29760 non-null  int64
 4   text_SizeOfRawData          29760 non-null  int64
 5   text_PointerToRawData       29760 non-null  int64
 6   text_PointerToRelocations   29760 non-null  int64
 7   text_PointerToLinenumbers   29760 non-null  int64
 8   text_NumberOfRelocations    29760 non-null  int64
 9   text_NumberOfLinenumbers    29760 non-null  int64
 10  text_Characteristics        29760 non-null  int64
 11  data_Misc_VirtualSize       29760 non-null  int64
 12  data_VirtualAddress         29760 non-null  int64
 13  data_SizeOfRawData          29760 non-null  int64
 14  data_PointerToRawData       29760 non-null  int64
 15  data_PointerToRelocations   29760 non-null  int64
 16  data_PointerToLinenumbers   29760 non-null  int64
 17  data_NumberOfRelocations    29760 non-null  int64
 18  data_NumberOfLinenumbers    29760 non-null  int64
 19  data_Characteristics        29760 non-null  int64
 20  rdata_Misc_VirtualSize      29760 non-null  int64
 21  rdata_VirtualAddress        29760 non-null  int64
 22  rdata_SizeOfRawData         29760 non-null  int64
 23  rdata_PointerToRawData      29760 non-null  int64
 24  rdata_PointerToRelocations  29760 non-null  int64
 25  rdata_PointerToLinenumbers  29760 non-null  int64
 26  rdata_NumberOfRelocations   29760 non-null  int64
 27  rdata_NumberOfLinenumbers   29760 non-null  int64
 28  rdata_Characteristics       29760 non-null  int64
 29  bss_Misc_VirtualSize        29760 non-null  int64
 30  bss_VirtualAddress          29760 non-null  int64
 31  bss_SizeOfRawData           29760 non-null  int64
 32  bss_PointerToRawData        29760 non-null  int64
 33  bss_PointerToRelocations    29760 non-null  int64
 34  bss_PointerToLinenumbers    29760 non-null  int64
 35  bss_NumberOfRelocations     29760 non-null  int64
 36  bss_NumberOfLinenumbers     29760 non-null  int64
 37  bss_Characteristics         29760 non-null  int64
 38  idata_Misc_VirtualSize      29760 non-null  int64
 39  idata_VirtualAddress        29760 non-null  int64
 40  idata_SizeOfRawData         29760 non-null  int64
 41  idata_PointerToRawData      29760 non-null  int64
 42  idata_PointerToRelocations  29760 non-null  int64
 43  idata_PointerToLinenumbers  29760 non-null  int64
 44  idata_NumberOfRelocations   29760 non-null  int64
 45  idata_NumberOfLinenumbers   29760 non-null  int64
 46  idata_Characteristics       29760 non-null  int64
 47  edata_Misc_VirtualSize      29760 non-null  int64
 48  edata_VirtualAddress        29760 non-null  int64
 49  edata_SizeOfRawData         29760 non-null  int64
 50  edata_PointerToRawData      29760 non-null  int64
 51  edata_PointerToRelocations  29760 non-null  int64
 52  edata_PointerToLinenumbers  29760 non-null  int64
 53  edata_NumberOfRelocations   29760 non-null  int64
 54  edata_NumberOfLinenumbers   29760 non-null  int64
 55  edata_Characteristics       29760 non-null  int64
 56  rsrc_Misc_VirtualSize       29760 non-null  int64
 57  rsrc_VirtualAddress         29760 non-null  int64
 58  rsrc_SizeOfRawData          29760 non-null  int64
 59  rsrc_PointerToRawData       29760 non-null  int64
 60  rsrc_PointerToRelocations   29760 non-null  int64
 61  rsrc_PointerToLinenumbers   29760 non-null  int64
 62  rsrc_NumberOfRelocations    29760 non-null  int64
 63  rsrc_NumberOfLinenumbers    29760 non-null  int64
 64  rsrc_Characteristics        29760 non-null  int64
 65  reloc_Misc_VirtualSize      29760 non-null  int64
 66  reloc_VirtualAddress        29760 non-null  int64
 67  reloc_SizeOfRawData         29760 non-null  int64
 68  reloc_PointerToRawData      29760 non-null  int64
 69  reloc_PointerToRelocations  29760 non-null  int64
 70  reloc_PointerToLinenumbers  29760 non-null  int64
 71  reloc_NumberOfRelocations   29760 non-null  int64
 72  reloc_NumberOfLinenumbers   29760 non-null  int64
 73  reloc_Characteristics       29760 non-null  int64
 74  tls_Misc_VirtualSize        29760 non-null  int64
 75  tls_VirtualAddress          29760 non-null  int64
 76  tls_SizeOfRawData           29760 non-null  int64
 77  tls_PointerToRawData        29760 non-null  int64
 78  tls_PointerToRelocations    29760 non-null  int64
 79  tls_PointerToLinenumbers    29760 non-null  int64
 80  tls_NumberOfRelocations     29760 non-null  int64
 81  tls_NumberOfLinenumbers     29760 non-null  int64
 82  tls_Characteristics         29760 non-null  int64
 83  pdata_Misc_VirtualSize      29760 non-null  int64
 84  pdata_VirtualAddress        29760 non-null  int64
 85  pdata_SizeOfRawData         29760 non-null  int64
 86  pdata_PointerToRawData      29760 non-null  int64
 87  pdata_PointerToRelocations  29760 non-null  int64
 88  pdata_PointerToLinenumbers  29760 non-null  int64
 89  pdata_NumberOfRelocations   29760 non-null  int64
 90  pdata_NumberOfLinenumbers   29760 non-null  int64
 91  pdata_Characteristics       29760 non-null  int64
dtypes: int64(90), object(1), uint8(1)
memory usage: 23.7 MB

Label Distribution
Type
4    5090
1    5047
3    4955
2    4864
5    4228
6    3699
0    1877
Name: count, dtype: int64

Top Missing Values
SHA256                       0
Type                         0
text_Misc_VirtualSize        0
text_VirtualAddress          0
text_SizeOfRawData           0
text_PointerToRawData        0
text_PointerToRelocations    0
text_PointerToLinenumbers    0
text_NumberOfRelocations     0
text_NumberOfLinenumbers     0
text_Characteristics         0
data_Misc_VirtualSize        0
data_VirtualAddress          0
data_SizeOfRawData           0
data_PointerToRawData        0
data_PointerToRelocations    0
data_PointerToLinenumbers    0
data_NumberOfRelocations     0
data_NumberOfLinenumbers     0
data_Characteristics         0
dtype: int64

Constant Columns
8
['bss_PointerToRelocations', 'bss_PointerToLinenumbers', 'bss_NumberOfRelocations', 'bss_NumberOfLinenumbers', 'pdata_PointerToRelocations', 'pdata_PointerToLinenumbers', 'pdata_NumberOfRelocations', 'pdata_NumberOfLinenumbers']

,Type,text_Misc_VirtualSize,text_VirtualAddress,text_SizeOfRawData,text_PointerToRawData,text_PointerToRelocations,text_PointerToLinenumbers,text_NumberOfRelocations,text_NumberOfLinenumbers,text_Characteristics,...,tls_Characteristics,pdata_Misc_VirtualSize,pdata_VirtualAddress,pdata_SizeOfRawData,pdata_PointerToRawData,pdata_PointerToRelocations,pdata_PointerToLinenumbers,pdata_NumberOfRelocations,pdata_NumberOfLinenumbers,pdata_Characteristics
count,29760.000000,2.976000e+04,2.976000e+04,2.976000e+04,2.976000e+04,2.976000e+04,2.976000e+04,29760.000000,29760.000000,2.976000e+04,...,2.976000e+04,2.976000e+04,2.976000e+04,29760.000000,2.976000e+04,29760.0,29760.0,29760.0,29760.0,2.976000e+04
mean,3.136223,3.330184e+05,9.844301e+03,3.320933e+05,4.487639e+03,2.054643e+05,5.017786e+04,1.837399,1.932695,1.462997e+09,...,1.257468e+08,3.634925e+02,4.205557e+03,126.018683,3.711226e+03,0.0,0.0,0.0,0.0,2.416933e+07
std,1.802487,6.750130e+05,8.736727e+04,6.737745e+05,5.991141e+04,2.675110e+07,8.584756e+06,227.523118,213.910180,4.933275e+08,...,6.243773e+08,2.011117e+04,9.049542e+04,3535.954393,8.777450e+04,0.0,0.0,0.0,0.0,1.707008e+08
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
25%,2.000000,3.102400e+04,4.096000e+03,3.020800e+04,5.120000e+02,0.000000e+00,0.000000e+00,0.000000,0.000000,1.610613e+09,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
50%,3.000000,1.496090e+05,4.096000e+03,1.495040e+05,1.024000e+03,0.000000e+00,0.000000e+00,0.000000,0.000000,1.610613e+09,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
75%,5.000000,4.873300e+05,8.192000e+03,4.843520e+05,1.024000e+03,0.000000e+00,0.000000e+00,0.000000,0.000000,1.610613e+09,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
max,6.000000,3.379818e+07,8.036352e+06,3.379866e+07,8.022528e+06,4.261479e+09,1.480939e+09,34048.000000,30144.000000,3.763339e+09,...,3.758096e+09,3.284992e+06,7.737344e+06,509025.000000,7.721984e+06,0.0,0.0,0.0,0.0,3.758096e+09